package org.mixxx;

import android.content.Context;
import android.media.midi.MidiDevice;
import android.media.midi.MidiDeviceInfo;
import android.media.midi.MidiInputPort;
import android.media.midi.MidiManager;
import android.media.midi.MidiOutputPort;
import android.media.midi.MidiReceiver;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.util.Log;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

/**
 * JNI bridge between the native Mixxx MIDI backend (AndroidMidiController)
 * and the android.media.midi framework.
 *
 * One static entry point per operation; native code drives everything:
 * listDevices(), open(), close(), receive(), send(), closeAll().
 *
 * NOTE: This text was autonomously generated by an AI agent.
 */
public final class MidiBridge {
    private static final String TAG = "MixxxMidi";
    private static final int MAX_QUEUED_MESSAGES = 4096;
    private static final long OPEN_TIMEOUT_MS = 5000;

    private static final Handler sMainHandler = new Handler(Looper.getMainLooper());
    private static volatile MidiManager sMidiManager;

    private MidiBridge() {
    }

    private static final class Message {
        final byte[] data;
        final long timestampNanos;

        Message(byte[] data, long timestampNanos) {
            this.data = data;
            this.timestampNanos = timestampNanos;
        }
    }

    private static final class Connection {
        MidiDevice device;
        MidiInputPort inputPort;
        MidiOutputPort outputPort;
        MidiReceiver receiver;
        final ConcurrentLinkedQueue<Message> queue = new ConcurrentLinkedQueue<>();
    }

    private static final Map<Integer, Connection> sConnections = new ConcurrentHashMap<>();

    public static void init(Context context) {
        if (context == null) {
            Log.w(TAG, "init called with null context");
            return;
        }
        sMidiManager = (MidiManager) context.getSystemService(Context.MIDI_SERVICE);
        Log.i(TAG, "MidiManager " + (sMidiManager != null ? "ready" : "unavailable"));
    }

    /** Returns a JSON array describing all visible MIDI devices. */
    public static String listDevices() {
        JSONArray array = new JSONArray();
        MidiManager mm = sMidiManager;
        if (mm == null) {
            return array.toString();
        }
        MidiDeviceInfo[] devices = mm.getDevices();
        if (devices == null) {
            return array.toString();
        }
        for (MidiDeviceInfo info : devices) {
            if (info.isPrivate()) {
                continue;
            }
            try {
                JSONObject o = new JSONObject();
                o.put("id", info.getId());
                o.put("type", info.getType());
                Bundle props = info.getProperties();
                o.put("name", props.getString(MidiDeviceInfo.PROPERTY_NAME, ""));
                o.put("manufacturer", props.getString(MidiDeviceInfo.PROPERTY_MANUFACTURER, ""));
                o.put("product", props.getString(MidiDeviceInfo.PROPERTY_PRODUCT, ""));
                o.put("version", props.getString(MidiDeviceInfo.PROPERTY_VERSION, ""));
                o.put("serial", props.getString(MidiDeviceInfo.PROPERTY_SERIAL_NUMBER, ""));
                o.put("inputPorts", info.getInputPortCount());
                o.put("outputPorts", info.getOutputPortCount());
                array.put(o);
            } catch (JSONException e) {
                Log.w(TAG, "unable to serialize device " + info.getId() + ": " + e);
            }
        }
        return array.toString();
    }

    /**
     * Opens the device and its first input and/or output port.
     *
     * @param deviceId   MidiDeviceInfo id
     * @param forInput   open a port to send data to the device
     * @param forOutput  open a port to receive data from the device
     * @return true if at least one port was opened
     */
    public static boolean open(int deviceId, boolean forInput, boolean forOutput) {
        MidiManager mm = sMidiManager;
        if (mm == null) {
            Log.w(TAG, "open: MidiManager unavailable");
            return false;
        }
        if (sConnections.containsKey(deviceId)) {
            return true;
        }
        if (Looper.myLooper() == Looper.getMainLooper()) {
            // openDevice() reports via a Handler; blocking here would deadlock.
            Log.e(TAG, "open must not be called on the main thread");
            return false;
        }
        MidiDeviceInfo info = findInfo(mm, deviceId);
        if (info == null) {
            Log.w(TAG, "open: device " + deviceId + " not found");
            return false;
        }

        final MidiDevice[] result = new MidiDevice[1];
        final CountDownLatch latch = new CountDownLatch(1);
        mm.openDevice(info, device -> {
            result[0] = device;
            latch.countDown();
        }, sMainHandler);
        try {
            if (!latch.await(OPEN_TIMEOUT_MS, TimeUnit.MILLISECONDS)) {
                Log.w(TAG, "open: timed out opening device " + deviceId);
                return false;
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            return false;
        }
        MidiDevice device = result[0];
        if (device == null) {
            Log.w(TAG, "open: openDevice returned null for " + deviceId);
            return false;
        }

        Connection conn = new Connection();
        conn.device = device;
        boolean opened = false;
        if (forOutput && info.getOutputPortCount() > 0) {
            MidiOutputPort out = device.openOutputPort(0);
            if (out != null) {
                conn.outputPort = out;
                conn.receiver = new MidiReceiver() {
                    @Override
                    public void onSend(byte[] data, int offset, int count, long timestamp) {
                        if (count <= 0) {
                            return;
                        }
                        ConcurrentLinkedQueue<Message> queue = conn.queue;
                        while (queue.size() >= MAX_QUEUED_MESSAGES) {
                            queue.poll();
                        }
                        queue.add(new Message(
                                Arrays.copyOfRange(data, offset, offset + count), timestamp));
                    }
                };
                out.connect(conn.receiver);
                opened = true;
            }
        }
        if (forInput && info.getInputPortCount() > 0) {
            MidiInputPort in = device.openInputPort(0);
            if (in != null) {
                conn.inputPort = in;
                opened = true;
            }
        }

        if (!opened) {
            closeConnection(conn);
            return false;
        }
        sConnections.put(deviceId, conn);
        Log.i(TAG, "opened device " + deviceId
                + " inputPort=" + (conn.inputPort != null)
                + " outputPort=" + (conn.outputPort != null));
        return true;
    }

    /** Closes the device, its ports and discards queued messages. */
    public static void close(int deviceId) {
        Connection conn = sConnections.remove(deviceId);
        if (conn == null) {
            return;
        }
        closeConnection(conn);
        Log.i(TAG, "closed device " + deviceId);
    }

    /** Closes every open connection. Safe to call multiple times. */
    public static void closeAll() {
        for (Integer deviceId : sConnections.keySet().toArray(new Integer[0])) {
            close(deviceId);
        }
    }

    /**
     * Polls one message chunk from the device queue.
     *
     * @param deviceId        the device to poll
     * @param timestampNanos  out parameter receiving the chunk timestamp (ns)
     * @return the raw MIDI bytes or null when the queue is empty
     */
    public static byte[] receive(int deviceId, long[] timestampNanos) {
        Connection conn = sConnections.get(deviceId);
        if (conn == null) {
            return null;
        }
        Message msg = conn.queue.poll();
        if (msg == null) {
            return null;
        }
        if (timestampNanos != null && timestampNanos.length > 0) {
            timestampNanos[0] = msg.timestampNanos;
        }
        return msg.data;
    }

    /** Sends raw MIDI bytes to the device. Returns true on success. */
    public static boolean send(int deviceId, byte[] data) {
        Connection conn = sConnections.get(deviceId);
        if (conn == null || conn.inputPort == null || data == null || data.length == 0) {
            return false;
        }
        try {
            conn.inputPort.send(data, 0, data.length);
            return true;
        } catch (IOException e) {
            Log.w(TAG, "send to device " + deviceId + " failed: " + e);
            return false;
        }
    }

    private static MidiDeviceInfo findInfo(MidiManager mm, int deviceId) {
        MidiDeviceInfo[] devices = mm.getDevices();
        if (devices == null) {
            return null;
        }
        for (MidiDeviceInfo info : devices) {
            if (info.getId() == deviceId) {
                return info;
            }
        }
        return null;
    }

    private static void closeConnection(Connection conn) {
        if (conn.outputPort != null && conn.receiver != null) {
            try {
                conn.outputPort.disconnect(conn.receiver);
            } catch (Exception e) {
                Log.w(TAG, "disconnect failed: " + e);
            }
        }
        if (conn.inputPort != null) {
            try {
                conn.inputPort.close();
            } catch (IOException e) {
                Log.w(TAG, "closing input port failed: " + e);
            }
        }
        if (conn.outputPort != null) {
            try {
                conn.outputPort.close();
            } catch (IOException e) {
                Log.w(TAG, "closing output port failed: " + e);
            }
        }
        if (conn.device != null) {
            try {
                conn.device.close();
            } catch (IOException e) {
                Log.w(TAG, "closing device failed: " + e);
            }
        }
    }
}
